[package]
name = "rs_battery_condition"
version = "0.1.0"
authors = ["Nathan McIntosh <natemcintosh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
chrono = "0.4"
rusqlite = "0.24"
